name: Update Ambershire Prices

on:
  schedule:
    # Запускать каждый понедельник в 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run price scraper
      run: python ambershire_full_scraper.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ambershire-prices-full.json
        git diff --staged --quiet || git commit -m "Auto-update Ambershire prices $(date +'%Y-%m-%d')"
        git push
